### ISSUE TITLE
Incompatibile routing due rewrite rules

### ISSUE THREAD

**Issue by petrleocompel** [jasonhancock/yii2-markdown-docs#2]
if you will use normal Yii2 rewrite rules

``` htaccess
    # use mod_rewrite for pretty URL support
    RewriteEngine on
    # If a directory or a file exists, use the request directly
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    # Otherwise forward the request to index.php
    RewriteRule . index.php
```

You cant have route `/docs/` because is dir. It will show you a list dir.
Same with files `/docs/index.md`. It will show the file directly.

**Comment by jasonhancock** [comment]
Put you document directory outside of your web root. I generally put mine at @app/docs

**Comment by petrleocompel** [comment]
Works only for advanced template :blush:  not everybody use it. 
My path is also @app/docs but  my @webroot is @app. 
I fixed all these things in my fork.
